# Generated by Django 3.2.12 on 2022-04-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_mobile_name_usertable_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertable',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
